CREATE DATABASE IF NOT EXISTS zt_gateway;
USE zt_gateway;

CREATE TABLE IF NOT EXISTS gateway_audit_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  request_id VARCHAR(128) NOT NULL,
  decision VARCHAR(32) NOT NULL,
  reason VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
